pop-os/cosmic-edit

- i18n/pt-BR/cosmic_edit.ftl
Hey! Just saw Jeremy's post on Mastodon and I wanted to help the project a bit. I've added some quick Brazilian Portuguese translations, however I don't know how to build cosmic-edit to check them out.
I hope this helps!
> Add pt-br translations

- i18n/pl/cosmic_edit.ftl
Translated the cosmic_edit.ftl to Polish.
> Add Polish translation

- i18n/de/cosmic_edit.ftl
German is _wide_, please let me know if that doesn't break anything ^^
> Add German translation

- i18n/lt/cosmic_edit.ftl
Me and my bf tried our best. I might come back and change some stuff if I notice any issues when the text editor is fully out or if anyone else reports any issues. :smiley:
Can't wait to experience all the cool stuff you guys are doing with COSMIC!
> Add Lithuanian translation

- i18n/fr/cosmic_edit.ftl
I checked and normally there is no overrun
> add frensh translation

- i18n/sr-Cyrl/cosmic_edit.ftl
- i18n/sr/cosmic_edit.ftl
The language codes should be correct now.
> Add Serbian Latin and Serbian Cyrillic translations

- i18n/sr-Cyrl/cosmic_edit.ftl
- i18n/sr/cosmic_edit.ftl
Not sure if this is the right way to edit translations. Let me know if there is a way without making a pull request. :)
> Add select-all for Serbian translation

- i18n/ru/cosmic_edit.ftl
> Added select-all

- i18n/el/cosmic_edit.ftl
Hello, please let me know if anything needs fixing here!
> Add Greek translation [i18n el]

- i18n/hu/cosmic_edit.ftl
Hope this works, please let me know if you need me to change anything.
> Add Hungarian translation

- i18n/it/cosmic_edit.ftl
Added translation for the new "Select all" entry
> Add italian translation for "Select all"

- .github/workflows/flakehub-publish-rolling.yml
This publishes the project to [FlakeHub](https://flakehub.com).
> Add FlakeHub file

- i18n/sv-SE/cosmic_edit.ftl
Swedish translation
if the folder name is wrong please feel free to change to the correct one for Swedish
> Add Swedish Translation

- i18n/tr/cosmic_edit.ftl
Thank you for your good efforts. I could always revise the translation as your program being build.
> Add Turkish translation

- i18n/sr-Cyrl/cosmic_edit.ftl
- i18n/sr-Latn/cosmic_edit.ftl
> Update Serbian translations

- i18n/hu/cosmic_edit.ftl
Some of the transleted terms are a bit long, let me know if you need me to come up with shorter versions.
> Add new translations to i18n/hu/cosmic_edit.ftl

- i18n/pl/cosmic_edit.ftl
Added git integration bits, changed themes for consistency reasons, changed recent to alternative word - overall it's really hard to translate it directly as there are no 100% correct replacement - ubiegły, przeszły are probably most fitting choices as ostatni means literally the one before and it give more than one choice. Correct would be Otwórz (open) jeden z ostatnich (one of the recent ones) plików (files), but that's bit too wordy. I don't have magic fix for that issue, i'm just raising it.
> Update cosmic_edit.ftl PL translation

- i18n/tr/cosmic_edit.ftl
Some minor changes, and new translations for new functions.
> Update turkish translations

- src/main.rs
- src/text_box.rs
- Condensed a unneeded match statement into a condensed if statement. 
- Fixed unneeded `f32` conversations for values that are already `f32`.
- Used the `matches!` macro for direct to boolean result.
- Clippy formatting.
> Various code cleanup.

- README.md
COSMIC Text Editor
Currently an incomplete **pre-alpha**, this project is a work in progress - issues are expected.
You can test by installing a current version of Rust and then building with `cargo`.
```SHELL
git clone https://github.com/pop-os/cosmic-edit
cd cosmic-edit
cargo build
```
You can get more detailed errors by using the `RUST_LOG` environment variables, that you can invoke for just that one command like this: `RUST_LOG=debug cargo run`. This will give you more detail about the application state. You can go even futher with `RUST_LOG=trace cargo run`, that shows all logging details about the applicaiton.
PRs are welcome, as it builds a better product for everyone. It is recomended that you check your code with Clippy Lints turned on. You can find more about [Configuring …
> Update readme for clippy and how to get more debug information.

- src/config.rs
- src/main.rs
Nothing fancy. These are just the tab navigation shortcuts from the other two programs.
> Port tab keyboard shortcuts over from cosmic-term and cosmic-files

- Cargo.lock
Brings in the improvement to correct padding of the pagination buttons, and make them reactive to hover events.
> fix: paginated tab button fixes

- i18n/ja/cosmic_edit.ftl
I had left some of the strings in English by mistake
> Update Japanese translation

- README.md
- i18n/sr-Cyrl/cosmic_edit.ftl
- i18n/sr-Latn/cosmic_edit.ftl
Also fixed minor typos in `README.md` .
> i18n(sr): Update Serbian translations

- i18n/ja/cosmic_edit.ftl
This is a temporary fix. Additional fixes will probably be needed in the future.
> Fix Japanese Translation

- i18n/sv-SE/cosmic_edit.ftl
> Update cosmic_edit.ftl - Update Swedish Translation

- Cargo.lock
- src/main.rs
Draft until winit change is merged
> Patches for redox

- i18n/ja/cosmic_edit.ftl
The word "management" could be translated two different ways depending on whether it is a synonym for "operation" (操作) or if it strictly means "management of an organization, business, etc." (管理) and both of these apply to repositories.
If this causes any confusion a discussion about translation conventions might be necessary.
> Added Git description and git loading to Japanese

- i18n/hu/cosmic_edit.ftl
- add translations to new items
- add more fitting translation to 'git-management' (the previous translation refered to a process rather than a tool)
> Update Hungarian translation

- i18n/de/cosmic_edit.ftl
note that the translations for "unstaged-changes" and "staged-changes" are not translated at all because both terms are used in German as well (I have never heard some one using German terms in this context)
> updated German translations

- src/main.rs
Closes: #174
This issue was my fault, so I may as well fix it.
I'll modify the dialog based on the design (I can't find it though). Here is how it looks for now:
Tab that has never been saved:
Open file with unsaved changes:
> fix: Unsaved changes prompt should be dialogs

- src/main.rs
> fix: focus the text box when the window gains focus

- i18n/zh-TW/cosmic_edit.ftl
> i18n(zh_TW): add Taiwanese translation

- i18n/de/cosmic_edit.ftl
Change "Ansehen" to "Ansicht".
In cosmic-terminal it also says “Ansicht”
This is my first request, I hope everything fits.
> Updated German translation

- src/main.rs
> Replace empty, unsaved, and activated tab on file load

- i18n/tr/cosmic_edit.ftl
Fix little mistakes and bring it closer to the established translations by the GNOME and KDE Turkish teams for consistency.
> Update Turkish translation

- i18n/fr/cosmic_edit.ftl
Hello,
This update includes the latest french translations for Cosmic Edit. Best regards,
Roxfr
> Updated french translation for Cosmic Edit

- src/tab.rs
Fixed bug where the selection wouldn't reset after finding or replacing text
Find menu now selects text being searched for
> Fixed selection bug when finding or replacing text

- Cargo.lock
- src/menu.rs
This makes the context menu use @space_s + 1.0, so that the corners match up properly with the menu.
> Fix content menu radius

- i18n/ga/cosmic_edit.ftl
Added Irish translation. 
(strings taken from i18n\en folder)
> Added Irish translation

- src/main.rs
> chore: remove forgotten eprintln.

- Cargo.lock
- Cargo.toml
- src/main.rs
fixes #312 
similar fix to: https://github.com/pop-os/cosmic-term/commit/c4cb09f18394913d8e76d1a336d10241b9b1da65
> perf: reduce disk io when updating config values.

- i18n/it/cosmic_edit.ftl
Added missing translation strings too
> (i18n) [IT] - Minor fixes

- i18n/es/cosmic_edit.ftl
Updated the spanish translation to match the english version at epoch 7, plus a few word fixes for coherence between components.
> i18n(es): Updated translation.

- Cargo.lock
- Cargo.toml
> pin cosmic-text to b017d7c

- src/tab.rs
Fixes #322 
Fixes issue where cosmic-edit would crash if user:
1. Opens existing file
2. Makes changes to file (But do not save)
3. Clicks File -> Revert all changes 
4. Triggers Undo (Either through the Edit menu or shortcut)
The fix refactors `reload` to properly track the revert operation in the editor's change history, allowing undo/redo. The fix requires bypassing editor.load_text with manual text replacement to properly track the entire operation as a single change. I tried getting change tracking to work with load_text() but didn't find a way to do it while also keeping the changes small.
> fix(322): fix undo/redo after reverting all changes

- Cargo.lock
- Cargo.toml
- src/main.rs
As noted in https://github.com/pop-os/cosmic-term/pull/540.
> Make dbus-config optional

- i18n/pl/cosmic_edit.ftl
> Update cosmic_edit.ftl PL translate About

- Cargo.lock
- Cargo.toml
- src/localize.rs
- src/project.rs
Reduces binary size by about 25 MB.
> Update to icu 2.0
